export const hospitalsBaseData = [
  {
    id: 1,
    name: 'City General Hospital',
    location: 'Downtown',
    totalDevices: 65,
    offline: 3,
    criticalAlerts: 2,
    status: 'healthy',
    healthData: [
      { name: 'Healthy', value: 58, color: '#10b981' },
      { name: 'Warning', value: 4, color: '#f59e0b' },
      { name: 'Critical', value: 3, color: '#ef4444' },
    ],
    deviceTypes: [
      { name: 'Ventilators', count: 18 },
      { name: 'Refrigerators', count: 15 },
      { name: 'Incubators', count: 12 },
      { name: 'UPS', count: 20 },
    ],
    temperatureBase: { min: 20, max: 25 },
    lastUpdated: '2 min ago',
  },
  {
    id: 2,
    name: 'Metro Central Medical',
    location: 'Midtown',
    totalDevices: 48,
    offline: 5,
    criticalAlerts: 5,
    status: 'warning',
    healthData: [
      { name: 'Healthy', value: 38, color: '#10b981' },
      { name: 'Warning', value: 7, color: '#f59e0b' },
      { name: 'Critical', value: 3, color: '#ef4444' },
    ],
    deviceTypes: [
      { name: 'Ventilators', count: 12 },
      { name: 'Refrigerators', count: 10 },
      { name: 'Incubators', count: 8 },
      { name: 'UPS', count: 18 },
    ],
    temperatureBase: { min: 21, max: 27 },
    lastUpdated: '1 min ago',
  },
  {
    id: 3,
    name: 'Westside Medical Center',
    location: 'West End',
    totalDevices: 42,
    offline: 1,
    criticalAlerts: 1,
    status: 'healthy',
    healthData: [
      { name: 'Healthy', value: 39, color: '#10b981' },
      { name: 'Warning', value: 2, color: '#f59e0b' },
      { name: 'Critical', value: 1, color: '#ef4444' },
    ],
    deviceTypes: [
      { name: 'Ventilators', count: 10 },
      { name: 'Refrigerators', count: 8 },
      { name: 'Incubators', count: 9 },
      { name: 'UPS', count: 15 },
    ],
    temperatureBase: { min: 19, max: 23 },
    lastUpdated: '3 min ago',
  },
  {
    id: 4,
    name: 'North Valley Hospital',
    location: 'North District',
    totalDevices: 30,
    offline: 7,
    criticalAlerts: 4,
    status: 'critical',
    healthData: [
      { name: 'Healthy', value: 19, color: '#10b981' },
      { name: 'Warning', value: 7, color: '#f59e0b' },
      { name: 'Critical', value: 4, color: '#ef4444' },
    ],
    deviceTypes: [
      { name: 'Ventilators', count: 8 },
      { name: 'Refrigerators', count: 6 },
      { name: 'Incubators', count: 5 },
      { name: 'UPS', count: 11 },
    ],
    temperatureBase: { min: 22, max: 29 },
    lastUpdated: '5 min ago',
  },
];
